symbols:
  - NASDAQ:NVDA
  - NASDAQ:MSFT
  - NASDAQ:AAPL
  - NASDAQ:AMZN
  - NASDAQ:META
  - NASDAQ:GOOGL
  - NASDAQ:GOOG
  - NASDAQ:AVGO
  - NASDAQ:AMD
  - NASDAQ:TSLA
  - NASDAQ:CSCO
  - NASDAQ:ADBE
  - NASDAQ:LITE
  - NASDAQ:AMAT
  - NASDAQ:ASML
  - NASDAQ:INTC
  - NASDAQ:QCOM
  - NASDAQ:MU
  - NASDAQ:MRVL
  - NASDAQ:KLAC
  - NASDAQ:LRCX
  - NASDAQ:CRWD
  - NASDAQ:ZS
  - NASDAQ:DDOG
  - NASDAQ:PLTR
  - NASDAQ:NFLX
  - NASDAQ:COST
  - NASDAQ:PEP
  - NASDAQ:LIN
  - NASDAQ:TXN
